### ISSUE TITLE
Server breaks when order fails

### ISSUE THREAD

**Issue by fennilin** [Andrew-Stein/exchange_simulator#5]
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54179)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "server.py", line 209, in do_GET
    get(self, routes)
  File "server.py", line 197, in get
    data = json.dumps(handler(routes, params)) + '\n'
  File "server.py", line 286, in handle_sell
    'avg_price': avg_price,
UnboundLocalError: local variable 'avg_price' referenced before assignment
----------------------------------------
```

avg_price not set when no results returned, breaks the code:
```
result   = clear_order(px, size, self._book[side], ops[side])
if result:
    self._book[side] = result[1]
    avg_price = round(result[0] / size, 2)
return {
    'id': x['id'],
    'side': x['side'],
    'timestamp': str(t),
    'avg_price': avg_price,
    'qty': avg_price and size,
}
```

**Comment by Wumpkins** [comment]
+1

**Comment by DavidWatkins** [comment]
+1
